### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by CamDavidsonPilon** [hrossman/pymsm#56]
👋 Hi folks, I'm the reviewer for your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/4422). I'll be making issues in this repo for my feedback. 

-----

1. Currently, github actions will only run automated tests (CI) on [pull requests](https://github.com/hrossman/pymsm/blob/main/.github/workflows/tests.yml#L3). I would suggest making this on `pull_request` _and_ `push`. Contributors will push to the main branch, and you want CI to run for these commits, too. 
2. There is installation instructions to install from pypi, but what about locally? I git pulled the repo, ran `pip3 install -e .`, and the `py.test` to test. That can be documented in a section on the README or the docs. 
3. tests in `test_msm_examples.py` and `test_sim.py` should assert some output. There should be a reason you are running a test - assert that. 
4. This can be fixed (found running py.test on my machine, py3.9.6)
```
src/pymsm/datasets/__init__.py:319
  /Users/camerondavidson-pilon/code/pymsm/src/pymsm/datasets/__init__.py:319: DeprecationWarning: invalid escape sequence \R
    1: "Discharged\Recovered",
``` 
5. If possible, try to fix the lifelines warnings that show up. Not always possible, I know.
6. `stepfunc` seems like an important function, but has lots of potential edge cases. This would be a good function to test as well.

**Comment by CamDavidsonPilon** [comment]
@hrossman what are your thoughts on the above? Any confusion about the provided feedback?

**Comment by hrossman** [comment]
Agree with all comments. Was waiting for all reviewers before we deal with all comments jointly. Thank you, we'll start working on these

**Comment by hrossman** [comment]
Issues status:
1. Fixed
2. Added local installation instructions to README
3. Added assertions
4. Fixed
5. Noted thanks. The one place they do show up is in the COVID example notebook, wheere we actually want to to show users how to deal with such a situation. We comment on that in the notebook as a precursor to the "transition trimming" procedure.
6. Indeed thanks. Added tests for `stepfunc` function now.
